#ifndef MTC_CONFIG_H
#define MTC_CONFIG_H


#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace mtc {

static const std::map<std::string, u_int32_t> MTC_KEY_MAPPING = {
    {"nr_free_pages", 0x0},
    {"nr_zone_inactive_anon", 0x1},
    {"nr_zone_active_anon", 0x2},
    {"nr_zone_inactive_file", 0x3},
    {"nr_zone_active_file", 0x4},
    {"nr_zone_unevictable", 0x5},
    {"nr_zone_write_pending", 0x6},
    {"nr_mlock", 0x7},
    {"nr_bounce", 0x8},
    {"nr_zspages", 0x9},
    {"nr_free_cma", 0xa},
    {"nr_unaccepted", 0xb},
    {"numa_hit", 0xc},
    {"numa_miss", 0xd},
    {"numa_foreign", 0xe},
    {"numa_interleave", 0xf},
    {"numa_local", 0x10},
    {"numa_other", 0x11},
    {"nr_inactive_anon", 0x12},
    {"nr_active_anon", 0x13},
    {"nr_inactive_file", 0x14},
    {"nr_active_file", 0x15},
    {"nr_unevictable", 0x16},
    {"nr_slab_reclaimable", 0x17},
    {"nr_slab_unreclaimable", 0x18},
    {"nr_isolated_anon", 0x19},
    {"nr_isolated_file", 0x1a},
    {"workingset_nodes", 0x1b},
    {"workingset_refault_anon", 0x1c},
    {"workingset_refault_file", 0x1d},
    {"workingset_activate_anon", 0x1e},
    {"workingset_activate_file", 0x1f},
    {"workingset_restore_anon", 0x20},
    {"workingset_restore_file", 0x21},
    {"workingset_nodereclaim", 0x22},
    {"nr_anon_pages", 0x23},
    {"nr_mapped", 0x24},
    {"nr_file_pages", 0x25},
    {"nr_dirty", 0x26},
    {"nr_writeback", 0x27},
    {"nr_writeback_temp", 0x28},
    {"nr_shmem", 0x29},
    {"nr_shmem_hugepages", 0x2a},
    {"nr_shmem_pmdmapped", 0x2b},
    {"nr_file_hugepages", 0x2c},
    {"nr_file_pmdmapped", 0x2d},
    {"nr_anon_transparent_hugepages", 0x2e},
    {"nr_dirty_threshold", 0x2f},
    {"nr_dirty_background_threshold", 0x30},
    {"pgpgin", 0x31},
    {"pgpgout", 0x32},
    {"pswpin", 0x33},
    {"pswpout", 0x34},
    {"pgfault", 0x35},
    {"pgmajfault", 0x36},
    {"pgalloc_dma", 0x37},
    {"pgalloc_dma32", 0x38},
    {"pgalloc_normal", 0x39},
    {"pgalloc_movable", 0x3a},
    {"pgalloc_device", 0x3b},
    {"allocstall_dma", 0x3c},
    {"allocstall_dma32", 0x3d},
    {"allocstall_normal", 0x3e},
    {"allocstall_movable", 0x3f},
    {"allocstall_device", 0x40},
    {"pgskip_dma", 0x41},
    {"pgskip_dma32", 0x42},
    {"pgskip_normal", 0x43},
    {"pgskip_movable", 0x44},
    {"pgskip_device", 0x45},
    {"pgfree", 0x46},
    {"pgactivate", 0x47},
    {"pgdeactivate", 0x48},
    {"pglazyfree", 0x49},
    {"pglazyfreed", 0x4a},
    {"pgrefill", 0x4b},
    {"pgreuse", 0x4c},
    {"pgsteal_kswapd", 0x4d},
    {"pgsteal_direct", 0x4e},
    {"pgsteal_khugepaged", 0x4f},
    {"pgscan_kswapd", 0x50},
    {"pgscan_direct", 0x51},
    {"pgscan_khugepaged", 0x52},
    {"pgscan_direct_throttle", 0x53},
    {"pgscan_anon", 0x54},
    {"pgscan_file", 0x55},
    {"pgsteal_anon", 0x56},
    {"pgsteal_file", 0x57},
    {"zone_reclaim_failed", 0x58},
    {"pginodesteal", 0x59},
    {"slabs_scanned", 0x5a},
    {"kswapd_inodesteal", 0x5b},
    {"kswapd_low_wmark_hit_quickly", 0x5c},
    {"kswapd_high_wmark_hit_quickly", 0x5d},
    {"pageoutrun", 0x5e},
    {"pgrotated", 0x5f},
    {"drop_pagecache", 0x60},
    {"drop_slab", 0x61},
    {"oom_kill", 0x62},
    {"numa_pte_updates", 0x63},
    {"numa_huge_pte_updates", 0x64},
    {"numa_hint_faults", 0x65},
    {"numa_hint_faults_local", 0x66},
    {"numa_pages_migrated", 0x67},
    {"pgmigrate_success", 0x68},
    {"pgmigrate_fail", 0x69},
    {"thp_migration_success", 0x6a},
    {"thp_migration_fail", 0x6b},
    {"thp_migration_split", 0x6c},
    {"compact_migrate_scanned", 0x6d},
    {"compact_free_scanned", 0x6e},
    {"compact_isolated", 0x6f},
    {"compact_stall", 0x70},
    {"compact_fail", 0x71},
    {"compact_success", 0x72},
    {"compact_daemon_wake", 0x73},
    {"compact_daemon_migrate_scanned", 0x74},
    {"compact_daemon_free_scanned", 0x75},
    {"htlb_buddy_alloc_success", 0x76},
    {"htlb_buddy_alloc_fail", 0x77},
    {"unevictable_pgs_culled", 0x78},
    {"unevictable_pgs_scanned", 0x79},
    {"unevictable_pgs_rescued", 0x7a},
    {"unevictable_pgs_mlocked", 0x7b},
    {"unevictable_pgs_munlocked", 0x7c},
    {"unevictable_pgs_cleared", 0x7d},
    {"unevictable_pgs_stranded", 0x7e},
    {"thp_fault_alloc", 0x7f},
    {"thp_fault_fallback", 0x80},
    {"thp_fault_fallback_charge", 0x81},
    {"thp_collapse_alloc", 0x82},
    {"thp_collapse_alloc_failed", 0x83},
    {"thp_file_alloc", 0x84},
    {"thp_file_fallback", 0x85},
    {"thp_file_fallback_charge", 0x86},
    {"thp_file_mapped", 0x87},
    {"thp_split_page", 0x88},
    {"thp_split_page_failed", 0x89},
    {"thp_deferred_split_page", 0x8a},
    {"thp_split_pmd", 0x8b},
    {"thp_scan_exceed_none_pte", 0x8c},
    {"thp_scan_exceed_swap_pte", 0x8d},
    {"thp_scan_exceed_share_pte", 0x8e},
    {"thp_split_pud", 0x8f},
    {"thp_zero_page_alloc", 0x90},
    {"thp_zero_page_alloc_failed", 0x91},
    {"thp_swpout", 0x92},
    {"thp_swpout_fallback", 0x93},
    {"balloon_inflate", 0x94},
    {"balloon_deflate", 0x95},
    {"balloon_migrate", 0x96},
    {"swap_ra", 0x97},
    {"swap_ra_hit", 0x98},
    {"ksm_swpin_copy", 0x99},
    {"cow_ksm", 0x9a},
    {"zswpin", 0x9b},
    {"zswpout", 0x9c},
    {"zswpwb", 0x9d},
    {"direct_map_level2_splits", 0x9e},
    {"direct_map_level3_splits", 0x9f},
    {"nr_unstable", 0xa0},
    {"total", 0xa1},
    {"free", 0xa2},
    {"available", 0xa3},
    {"buffers", 0xa4},
    {"cached", 0xa5},
    {"swapCache", 0xa6},
    {"active", 0xa7},
    {"inActive", 0xa8},
    {"activeAnon", 0xa9},
    {"inActiveAnon", 0xaa},
    {"activeFile", 0xab},
    {"inActiveFile", 0xac},
    {"unevictable", 0xad},
    {"mLocked", 0xae},
    {"swapTotal", 0xaf},
    {"swapFree", 0xb0},
    {"zswap", 0xb1},
    {"zswapped", 0xb2},
    {"dirty", 0xb3},
    {"writeback", 0xb4},
    {"pagesAnon", 0xb5},
    {"pageMapped", 0xb6},
    {"shmem", 0xb7},
    {"kreClaimable", 0xb8},
    {"slab", 0xb9},
    {"srClaimable", 0xba},
    {"sunReclaim", 0xbb},
    {"kernelStack", 0xbc},
    {"pageTables", 0xbd},
    {"secPageTables", 0xbe},
    {"nfsUnstable", 0xbf},
    {"bounce", 0xc0},
    {"writebackTmp", 0xc1},
    {"commitLimit", 0xc2},
    {"committedAllocs", 0xc3},
    {"vmallocTotal", 0xc4},
    {"vmallocUsed", 0xc5},
    {"vmallocChunk", 0xc6},
    {"perCPU", 0xc7},
    {"hardwareCorrupted", 0xc8},
    {"hugePagesAnon", 0xc9},
    {"hugePagesShmem", 0xca},
    {"pmdMappedShmem", 0xcb},
    {"hugePagesFile", 0xcc},
    {"pmdMappedFile", 0xcd},
    {"unaccepted", 0xce},
    {"hugePagesTotal", 0xcf},
    {"hugePagesFree", 0xd0},
    {"hugePagesRsvd", 0xd1},
    {"hugePagesSurp", 0xd2},
    {"hugePageSize", 0xd3},
    {"hugePageTLB", 0xd4},
    {"directMap4k", 0xd5},
    {"directMap2M", 0xd6},
    {"directMap1G", 0xd7},
    {"oomAdj", 0xd8},
    {"oomScore", 0xd9},
    {"oomScoreAdj", 0xda},
    {"p_size", 0xdb},
    {"p_resident", 0xdc},
    {"p_shared", 0xdd},
    {"p_text", 0xde},
    {"p_data", 0xdf},
    {"p_dirty", 0xe0},
};
static const std::map<uint32_t, std::string> MTC_INDEX_MAPPING {
    { 0x0, "nr_free_pages" },
    { 0x1, "nr_zone_inactive_anon" },
    { 0x2, "nr_zone_active_anon" },
    { 0x3, "nr_zone_inactive_file" },
    { 0x4, "nr_zone_active_file" },
    { 0x5, "nr_zone_unevictable" },
    { 0x6, "nr_zone_write_pending" },
    { 0x7, "nr_mlock" },
    { 0x8, "nr_bounce" },
    { 0x9, "nr_zspages" },
    { 0xa, "nr_free_cma" },
    { 0xb, "nr_unaccepted" },
    { 0xc, "numa_hit" },
    { 0xd, "numa_miss" },
    { 0xe, "numa_foreign" },
    { 0xf, "numa_interleave" },
    { 0x10, "numa_local" },
    { 0x11, "numa_other" },
    { 0x12, "nr_inactive_anon" },
    { 0x13, "nr_active_anon" },
    { 0x14, "nr_inactive_file" },
    { 0x15, "nr_active_file" },
    { 0x16, "nr_unevictable" },
    { 0x17, "nr_slab_reclaimable" },
    { 0x18, "nr_slab_unreclaimable" },
    { 0x19, "nr_isolated_anon" },
    { 0x1a, "nr_isolated_file" },
    { 0x1b, "workingset_nodes" },
    { 0x1c, "workingset_refault_anon" },
    { 0x1d, "workingset_refault_file" },
    { 0x1e, "workingset_activate_anon" },
    { 0x1f, "workingset_activate_file" },
    { 0x20, "workingset_restore_anon" },
    { 0x21, "workingset_restore_file" },
    { 0x22, "workingset_nodereclaim" },
    { 0x23, "nr_anon_pages" },
    { 0x24, "nr_mapped" },
    { 0x25, "nr_file_pages" },
    { 0x26, "nr_dirty" },
    { 0x27, "nr_writeback" },
    { 0x28, "nr_writeback_temp" },
    { 0x29, "nr_shmem" },
    { 0x2a, "nr_shmem_hugepages" },
    { 0x2b, "nr_shmem_pmdmapped" },
    { 0x2c, "nr_file_hugepages" },
    { 0x2d, "nr_file_pmdmapped" },
    { 0x2e, "nr_anon_transparent_hugepages" },
    { 0x2f, "nr_dirty_threshold" },
    { 0x30, "nr_dirty_background_threshold" },
    { 0x31, "pgpgin" },
    { 0x32, "pgpgout" },
    { 0x33, "pswpin" },
    { 0x34, "pswpout" },
    { 0x35, "pgfault" },
    { 0x36, "pgmajfault" },
    { 0x37, "pgalloc_dma" },
    { 0x38, "pgalloc_dma32" },
    { 0x39, "pgalloc_normal" },
    { 0x3a, "pgalloc_movable" },
    { 0x3b, "pgalloc_device" },
    { 0x3c, "allocstall_dma" },
    { 0x3d, "allocstall_dma32" },
    { 0x3e, "allocstall_normal" },
    { 0x3f, "allocstall_movable" },
    { 0x40, "allocstall_device" },
    { 0x41, "pgskip_dma" },
    { 0x42, "pgskip_dma32" },
    { 0x43, "pgskip_normal" },
    { 0x44, "pgskip_movable" },
    { 0x45, "pgskip_device" },
    { 0x46, "pgfree" },
    { 0x47, "pgactivate" },
    { 0x48, "pgdeactivate" },
    { 0x49, "pglazyfree" },
    { 0x4a, "pglazyfreed" },
    { 0x4b, "pgrefill" },
    { 0x4c, "pgreuse" },
    { 0x4d, "pgsteal_kswapd" },
    { 0x4e, "pgsteal_direct" },
    { 0x4f, "pgsteal_khugepaged" },
    { 0x50, "pgscan_kswapd" },
    { 0x51, "pgscan_direct" },
    { 0x52, "pgscan_khugepaged" },
    { 0x53, "pgscan_direct_throttle" },
    { 0x54, "pgscan_anon" },
    { 0x55, "pgscan_file" },
    { 0x56, "pgsteal_anon" },
    { 0x57, "pgsteal_file" },
    { 0x58, "zone_reclaim_failed" },
    { 0x59, "pginodesteal" },
    { 0x5a, "slabs_scanned" },
    { 0x5b, "kswapd_inodesteal" },
    { 0x5c, "kswapd_low_wmark_hit_quickly" },
    { 0x5d, "kswapd_high_wmark_hit_quickly" },
    { 0x5e, "pageoutrun" },
    { 0x5f, "pgrotated" },
    { 0x60, "drop_pagecache" },
    { 0x61, "drop_slab" },
    { 0x62, "oom_kill" },
    { 0x63, "numa_pte_updates" },
    { 0x64, "numa_huge_pte_updates" },
    { 0x65, "numa_hint_faults" },
    { 0x66, "numa_hint_faults_local" },
    { 0x67, "numa_pages_migrated" },
    { 0x68, "pgmigrate_success" },
    { 0x69, "pgmigrate_fail" },
    { 0x6a, "thp_migration_success" },
    { 0x6b, "thp_migration_fail" },
    { 0x6c, "thp_migration_split" },
    { 0x6d, "compact_migrate_scanned" },
    { 0x6e, "compact_free_scanned" },
    { 0x6f, "compact_isolated" },
    { 0x70, "compact_stall" },
    { 0x71, "compact_fail" },
    { 0x72, "compact_success" },
    { 0x73, "compact_daemon_wake" },
    { 0x74, "compact_daemon_migrate_scanned" },
    { 0x75, "compact_daemon_free_scanned" },
    { 0x76, "htlb_buddy_alloc_success" },
    { 0x77, "htlb_buddy_alloc_fail" },
    { 0x78, "unevictable_pgs_culled" },
    { 0x79, "unevictable_pgs_scanned" },
    { 0x7a, "unevictable_pgs_rescued" },
    { 0x7b, "unevictable_pgs_mlocked" },
    { 0x7c, "unevictable_pgs_munlocked" },
    { 0x7d, "unevictable_pgs_cleared" },
    { 0x7e, "unevictable_pgs_stranded" },
    { 0x7f, "thp_fault_alloc" },
    { 0x80, "thp_fault_fallback" },
    { 0x81, "thp_fault_fallback_charge" },
    { 0x82, "thp_collapse_alloc" },
    { 0x83, "thp_collapse_alloc_failed" },
    { 0x84, "thp_file_alloc" },
    { 0x85, "thp_file_fallback" },
    { 0x86, "thp_file_fallback_charge" },
    { 0x87, "thp_file_mapped" },
    { 0x88, "thp_split_page" },
    { 0x89, "thp_split_page_failed" },
    { 0x8a, "thp_deferred_split_page" },
    { 0x8b, "thp_split_pmd" },
    { 0x8c, "thp_scan_exceed_none_pte" },
    { 0x8d, "thp_scan_exceed_swap_pte" },
    { 0x8e, "thp_scan_exceed_share_pte" },
    { 0x8f, "thp_split_pud" },
    { 0x90, "thp_zero_page_alloc" },
    { 0x91, "thp_zero_page_alloc_failed" },
    { 0x92, "thp_swpout" },
    { 0x93, "thp_swpout_fallback" },
    { 0x94, "balloon_inflate" },
    { 0x95, "balloon_deflate" },
    { 0x96, "balloon_migrate" },
    { 0x97, "swap_ra" },
    { 0x98, "swap_ra_hit" },
    { 0x99, "ksm_swpin_copy" },
    { 0x9a, "cow_ksm" },
    { 0x9b, "zswpin" },
    { 0x9c, "zswpout" },
    { 0x9d, "zswpwb" },
    { 0x9e, "direct_map_level2_splits" },
    { 0x9f, "direct_map_level3_splits" },
    { 0xa0, "nr_unstable" },
    { 0xa1, "total" },
    { 0xa2, "free" },
    { 0xa3, "available" },
    { 0xa4, "buffers" },
    { 0xa5, "cached" },
    { 0xa6, "swapCache" },
    { 0xa7, "active" },
    { 0xa8, "inActive" },
    { 0xa9, "activeAnon" },
    { 0xaa, "inActiveAnon" },
    { 0xab, "inActiveAnon"},
    { 0xac, "activeFile"},
    { 0xad, "inActiveFile"},
    { 0xae, "unevictable"},
    { 0xaf, "mlock"},
    { 0xb0, "mapped"},
    { 0xb1, "dirty"},
    { 0xb2, "writeback"},
    { 0xb3, "filePages"},
    { 0xb4, "slab"},
    { 0xb5, "slabReclaimable"},
    { 0xb6, "slabUnreclaimable"},
    { 0xb7, "pageTables"},
    { 0xb8, "nfsUnstable"},
    { 0xb9, "bounce"},
    { 0xba, "writebackTmp"},
    { 0xbb, "commitLimit"},
    { 0xbc, "committedAs"},
    { 0xbd, "vmallocTotal"},
    { 0xbe, "vmallocUsed"},
    { 0xbf, "vmallocChunk"},
    { 0xc0, "hardwareCorrupted"},
    { 0xc1, "anonHugePages"},
    { 0xc2, "shmemHugePages"},
    { 0xc3, "shmemPmdMapped"},
    { 0xc4, "hugePagesTotal"},
    { 0xc5, "hugePagesFree"},
    { 0xc6, "hugePagesRsvd"},
    { 0xc7, "hugePagesSurp"},
    { 0xc8, "hugePageSize"},
    { 0xc9, "hugetlb"},
    { 0xca, "directMap4k"},
    { 0xcb, "directMap2M"},
    { 0xcc, "directMap1G"},
    {0xcd, "pmdMappedFile"},
    {0xce, "unaccepted"},
    {0xcf, "hugePagesTotal"},
    {0xd0, "hugePagesFree"},
    {0xd1, "hugePagesRsvd"},
    {0xd2, "hugePagesSurp"},
    {0xd3, "hugePageSize"},
    {0xd4, "hugePageTLB"},
    {0xd5, "directMap4k"},
    {0xd6, "directMap2M"},
    {0xd7, "directMap1G"},
    {0xd8, "oomAdj"},
    {0xd9, "oomScore"},
    {0xda, "oomScoreAdj"},
    {0xdb, "p_size"},
    {0xdc, "p_resident"},
    {0xdd, "p_shared"},
    {0xde, "p_text"},
    {0xdf, "p_data"},
    {0xe0, "p_dirty"},
};

struct MtcCategories {
    std::string name;
    std::vector<u_int32_t> ids;
};

const static std::vector<MtcCategories> MTC_CATEGORIES = {
    {"General", {0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6}},
    {"Active", {0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac}},
    {"State", {0xad, 0xae}},
    {"Swap", {0xaf, 0xb0, 0xb1, 0xb2}},
    {"Dirty & Writeback", {0xb3, 0xb4}},
    {"Page Usage", {0xb5, 0xb6}},
    {"Shared & Slab", {0xb7, 0xb8}},
    {"Kernel stack & Page tables", {0xbc, 0xbd, 0xbe, 0xbf}},
    {"Allocation commit", {0xc2, 0xc3}},
    {"Virtual Allocation", {0xc4, 0xc5, 0xc6}},
    {"Hardware", {0xc7, 0xc8}},
    {"Huge pages", {0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4}},
    {"Direct Mapping", {0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf}},
    {"Zone stats", {0x0, 0x1, 0x2, 0x3,0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xa}},
    {"NUMA stats", {0xc, 0xd, 0xe, 0xf, 0x10, 0x11}},
    {"Page Usage", {0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a}},
    {"Working set", {0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22}},
    {"Anonymous & file pages", {0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e}},
    {"Dirty & writeback thresholds", {0x2f, 0x30}},
    {"Page reclaim & fault", {0x31, 0x32, 0x33, 0x34, 0x35, 0x36}},
    {"Page allocation", {0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40}},
    {"Stealing & Scanning", {0x4d, 0x4e, 0x4f, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57}},
    {"Zone reclaim & kswapd", {0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f, 0x60, 0x61, 0x62}},
    {"NUMA & migration", {0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c}},
    {"Compaction stats", {0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75}},
    {"High order allocation", {0x76, 0x77}},
    {"Unevictable page", {0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e}},
    {"Transparent hugepage states", {0x7f, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93}},
    {"Ballooning", {0x94, 0x95, 0x96}},
    {"Swap & Zswap", {0x97, 0x98, 0x99, 0x9a, 0x9b, 0x9c, 0x9d}},
    {"Kernel Samepage Merging (KSM)", {0x99, 0x9a}},
    {"Direct map splits", {0x9e, 0x9f}}
};



}

#endif //MTC_CONFIG_H