name: Build and Test Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Build Main Target
        run: |
          make

      - name: Upload mem_monitor artifact
        uses: actions/upload-artifact@v3
        with:
          name: mem_monitor
          path: ./mem_monitor

  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential lcov

      - name: Build Test Target
        run: |
          make test

      - name: Upload mem_monitor_test and coverage files
        uses: actions/upload-artifact@v3
        with:
          name: mem_monitor_test
          path: |
            ./mem_monitor_test
            ./source/*.gcno
            ./tests/*.gcno
            ./*.gcda

  build-mem-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Build Main Target
        run: |
          cd memory-tracker
          make

      - name: Upload lib_mem_tracker artifact
        uses: actions/upload-artifact@v3
        with:
          name: lib_mem_tracker
          path: ./lib_mem_tracker.so

  build-mem-tracker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Build Main Target
        run: |
          cd memory-tracker
          make test

      - name: Upload mem_tracker_test artifact
        uses: actions/upload-artifact@v3
        with:
          name: mem_tracker_test
          path: ./mem_tracker_test

  run-tests:
    runs-on: ubuntu-latest
    needs: [build-main, build-test]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download mem_monitor_test artifact
        uses: actions/download-artifact@v3
        with:
          name: mem_monitor_test

      - name: Set execute permissions
        run: |
          chmod +x ./mem_monitor_test

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential lcov

      - name: Run Tests
        run: |
          ./mem_monitor_test

      - name: Collect Coverage Data
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate HTML Coverage Report
        run: |
          genhtml coverage.info --output-directory coverage-report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report



  run-mem-c-tracker-tests:
    runs-on: ubuntu-latest
    needs: [ build-mem-tracker, build-mem-tracker-test ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download lib_mem_tracker artifact
        uses: actions/download-artifact@v3
        with:
          name: lib_mem_tracker

      - name: Download mem_tracker_test artifact
        uses: actions/download-artifact@v3
        with:
          name: mem_tracker_test

      - name: Set execute permissions
        run: |
          chmod +x ./mem_tracker_test

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r memory-tracker/requirement.txt

      - name: Run C Tests
        run: |
          ./mem_tracker_test

      - name: Upload test output file
        uses: actions/upload-artifact@v3
        with:
          name: c-test-output-file
          path: memory_tracker.tmtc

  run-mem-python-tracker-tests:
    runs-on: ubuntu-latest
    needs: [ run-mem-c-tracker-tests ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download c-test-output-file artifact
        uses: actions/download-artifact@v3
        with:
          name: c-test-output-file

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r memory-tracker/requirement.txt

      - name: Run PyTests
        run: |
          pytest memory-tracker/test-output.py
